### ISSUE TITLE
Throw InvalidOperationException When Ignore only one table

### ISSUE THREAD

**Issue by bnn00023** [jbogard/Respawn#81]
As stated in the title.

``` C#
using System;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Respawn;

public class Program
{
    public static async Task Main(string[] args)
    {
        var connection = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\bnn00\source\repos\ConsoleApp1\ConsoleApp1\Database1.mdf;Integrated Security=True";
        using var conn = new SqlConnection(connection);
        try
        {
            await conn.OpenAsync();
        }
        catch (Exception)
        {

            throw;
        }
        await checkpoint.Reset(conn);
        await conn.ExecuteAsync(@"insert into TableAAA (id) values (20)");
        var aa = conn.Query<int>(@"select id from TableAAA");
        aa.ToList().ForEach(e => Console.WriteLine(e));
    }

    private static Checkpoint checkpoint = new Checkpoint
    {
        TablesToIgnore = new[] { "TableAAA" }
    };
}
```

Exception Stack
```
System.InvalidOperationException
  HResult=0x80131509
  Message=BeginExecuteNonQuery: CommandText property has not been initialized
  Source=System.Data.SqlClient
  StackTrace: 
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQuery(AsyncCallback callback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Respawn.Checkpoint.<ExecuteDeleteSqlAsync>d__49.MoveNext() in C:\Users\bnn00\source\repos\ConsoleApp1\Respawn-master\Respawn\Checkpoint.cs:line 84
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Respawn.Checkpoint.<Reset>d__47.MoveNext() in C:\Users\bnn00\source\repos\ConsoleApp1\Respawn-master\Respawn\Checkpoint.cs:line 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\Users\bnn00\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 27
```

**Comment by bnn00023** [comment]
I find same Issue #46
